CREATE TABLE [catalogue].[resources_resource_views] (

	[_link] varchar(8000) NULL, 
	[_link_resources] varchar(8000) NULL, 
	[_link_main] varchar(8000) NULL, 
	[date_format] varchar(8000) NULL, 
	[description] varchar(8000) NULL, 
	[description_fr] varchar(8000) NULL, 
	[ellipsis_length] float NULL, 
	[filterable] bit NULL, 
	[id] varchar(8000) NULL, 
	[package_id] varchar(8000) NULL, 
	[resource_id] varchar(8000) NULL, 
	[responsive] bit NULL, 
	[title] varchar(8000) NULL, 
	[title_fr] varchar(8000) NULL, 
	[view_type] varchar(8000) NULL, 
	[main_id] varchar(8000) NULL, 
	[resources_id] varchar(8000) NULL, 
	[show_fields] varchar(8000) NULL, 
	[bookmarks_pane] bit NULL, 
	[filter_pane] bit NULL, 
	[filter_pane_collapse] bit NULL, 
	[nav_pane] bit NULL, 
	[nav_pane_position] float NULL, 
	[report_id_en] varchar(8000) NULL, 
	[report_id_fr] varchar(8000) NULL
);