CREATE TABLE [MunicipalFinances].[mf_mr3_mill_rate] (

	[YEAR] float NULL, 
	[STATUS] varchar(8000) NULL, 
	[CODE] float NULL, 
	[MUNICIPALITY] varchar(8000) NULL, 
	[General_Municipal_Tax_Rates] float NULL, 
	[Residential] float NULL, 
	[Farmland] float NULL, 
	[Non-Residential_including_linear] float NULL, 
	[Non-Residential_small_business] float NULL, 
	[Machinery_and_Equipment] float NULL, 
	[Other_including_annexed_vacant_total_minimum_tax_etc.] float NULL, 
	[Requisitions_MGA_s._3261_] float NULL, 
	[Education_ASSF] float NULL, 
	[Residential_and_Farmland] float NULL, 
	[Non-Residential] float NULL, 
	[Education_Separate] float NULL, 
	[Has_a_supplementary_property_assessment] float NULL, 
	[Repealed_a_supplementary_property_assessment] float NULL, 
	[Total_Amount_Raised_by_Taxation_excluding_requisitions] float NULL, 
	[Total_Requisition_including_under/over_levy] float NULL, 
	[Residential_and_Farmland.1] float NULL, 
	[Non-Residential.1] float NULL, 
	[Other_Education_annexed_etc] float NULL, 
	[Seniors] float NULL, 
	[Lodge_Accommodation] float NULL, 
	[Designated_Industrial_Properties_DIP] float NULL, 
	[Non-Collection_Allowance] float NULL
);