CREATE TABLE [MunicipalFinances].[mf_p1_total] (

	[YEAR] float NULL, 
	[STATUS] varchar(8000) NULL, 
	[CODE] float NULL, 
	[MUNICIPALITY] varchar(8000) NULL, 
	[Cash_and_Temporary_Investments] float NULL, 
	[Municipal_Sustainability_Initiative_Capital_] float NULL, 
	[Municipal_Sustainability_Initiative_Operating] float NULL, 
	[Canada_Community-Building_Fund_CCBF] float NULL, 
	[Alberta_Community_Partnership-_Intermunicipal_Collaboration] float NULL, 
	[Alberta_Community_Partnership-_Municipal_Restructuring] float NULL, 
	[Alberta_Community_Partnership-_Mediation_and_Cooperative_Processes] float NULL, 
	[Alberta_Community_Partnership-_Municipal_Internship] float NULL, 
	[Alberta_Community_Partnership-_Local_Land_Use_Planning_] float NULL, 
	[Alberta_Community_Partnership-_Strategic_Initiative] float NULL, 
	[Alberta_Community_Partnership-_Regional_Collaboration_Program] float NULL, 
	[Other_Grants] float NULL, 
	[Local_Government_Fiscal_Framework] float NULL, 
	[Total_Restricted_Cash] float NULL, 
	[Unrestricted_Cash] float NULL, 
	[Accounts_Receivable_-_Grants] float NULL, 
	[Deferred_Revenue] float NULL, 
	[Municipal_Sustainability_Initiative_Capital_.1] float NULL, 
	[Municipal_Sustainability_Initiative_Operating.1] float NULL, 
	[Canada_Community-Building_Fund_CCBF.1] float NULL, 
	[Alberta_Community_Partnership-_Intermunicipal_Collaboration.1] float NULL, 
	[Alberta_Community_Partnership-_Municipal_Restructuring.1] float NULL, 
	[Alberta_Community_Partnership-_Mediation_and_Cooperative_Processes.1] float NULL, 
	[Alberta_Community_Partnership-_Municipal_Internship.1] float NULL, 
	[Alberta_Community_Partnership-_Local_Land_Use_Planning_.1] float NULL, 
	[Alberta_Community_Partnership-_Strategic_Initiative.1] float NULL, 
	[Alberta_Community_Partnership-_Regional_Collaboration_Program.1] float NULL, 
	[Other_Grants.1] float NULL, 
	[Local_Government_Fiscal_Framework.1] float NULL, 
	[Total_Deferred_Revenue_by_Grant] float NULL, 
	[Other_Deferred_Revenue] float NULL
);